[package]
name = "day23"
version = "0.1.0"
edition = "2018"
authors = ["James Wilson"]

[[bin]]
name = "day23"
path = "solution/day23.rs"

[[bin]]
name = "day23alt"
path = "solution/day23alt.rs"

[dependencies]
lazy_static = "1"
regex = "1"
rayon = "1"